#[allow(clippy::type_complexity)]
#[rustfmt::skip]
pub fn jobs() -> &'static [(fn(&str) -> u32, &'static str, &'static str)] {
    &[
        (day01::part1, "Day01, part 1", include_str!("../../day01/input")),
        (day01::part2, "Day01, part 2", include_str!("../../day01/input")),
        (day02::part1, "Day02, part 1", include_str!("../../day02/input")),
        (day02::part2, "Day02, part 2", include_str!("../../day02/input")),
        (day03::part1, "Day03, part 1", include_str!("../../day03/input")),
        (day03::part2, "Day03, part 2", include_str!("../../day03/input")),
        (day04::part1, "Day04, part 1", include_str!("../../day04/input")),
        (day04::part2, "Day04, part 2", include_str!("../../day04/input")),
        // (day05::part1, "Day05, part 1", include_str!("../../day05/input")),
        // (day05::part2, "Day05, part 2", include_str!("../../day05/input")),
        // (day06::part1, "Day06, part 1", include_str!("../../day06/input")),
        // (day06::part2, "Day06, part 2", include_str!("../../day06/input")),
        // (day07::part1, "Day07, part 1", include_str!("../../day07/input")),
        // (day07::part2, "Day07, part 2", include_str!("../../day07/input")),
        // (day08::part1, "Day08, part 1", include_str!("../../day08/input")),
        // (day08::part2, "Day08, part 2", include_str!("../../day08/input")),
        // (day09::part1, "Day09, part 1", include_str!("../../day09/input")),
        // (day09::part2, "Day09, part 2", include_str!("../../day09/input")),
        // (day10::part1, "Day10, part 1", include_str!("../../day10/input")),
        // (day10::part2, "Day10, part 2", include_str!("../../day10/input")),
        // (day11::part1, "Day11, part 1", include_str!("../../day11/input")),
        // (day11::part2, "Day11, part 2", include_str!("../../day11/input")),
        // (day12::part1, "Day12, part 1", include_str!("../../day12/input")),
        // (day12::part2, "Day12, part 2", include_str!("../../day12/input")),
        // (day13::part1, "Day13, part 1", include_str!("../../day13/input")),
        // (day13::part2, "Day13, part 2", include_str!("../../day13/input")),
        // (day14::part1, "Day14, part 1", include_str!("../../day14/input")),
        // (day14::part2, "Day14, part 2", include_str!("../../day14/input")),
        // (day15::part1, "Day15, part 1", include_str!("../../day15/input")),
        // (day15::part2, "Day15, part 2", include_str!("../../day15/input")),
        // (day16::part1, "Day16, part 1", include_str!("../../day16/input")),
        // (day16::part2, "Day16, part 2", include_str!("../../day16/input")),
        // (day17::part1, "Day17, part 1", include_str!("../../day17/input")),
        // (day17::part2, "Day17, part 2", include_str!("../../day17/input")),
        // (day18::part1, "Day18, part 1", include_str!("../../day18/input")),
        // (day18::part2, "Day18, part 2", include_str!("../../day18/input")),
        // (day19::part1, "Day19, part 1", include_str!("../../day19/input")),
        // (day19::part2, "Day19, part 2", include_str!("../../day19/input")),
        // (day20::part1, "Day20, part 1", include_str!("../../day20/input")),
        // (day20::part2, "Day20, part 2", include_str!("../../day20/input")),
        // (day21::part1, "Day21, part 1", include_str!("../../day21/input")),
        // (day21::part2, "Day21, part 2", include_str!("../../day21/input")),
        // (day22::part1, "Day22, part 1", include_str!("../../day22/input")),
        // (day22::part2, "Day22, part 2", include_str!("../../day22/input")),
        // (day23::part1, "Day23, part 1", include_str!("../../day23/input")),
        // (day23::part2, "Day23, part 2", include_str!("../../day23/input")),
        // (day24::part1, "Day24, part 1", include_str!("../../day24/input")),
        // (day24::part2, "Day24, part 2", include_str!("../../day24/input")),
        // (day25::part1, "Day25, part 1", include_str!("../../day25/input")),
    ]
}
